Enhancement/40 file visualizer backend connection
INDAPlus20/sahlest-emilsjol-nodelius-project pull request #44
Opened 2021-05-14 19:57 UTC by emilsjol

#40 
Istället för att Canvas.js visualiserar en lokalt genererad matris får den istället en matris från go-backend att visualisera.
Nu kan man bara plugga in en mer intressant matris i go-backenden så kan den visualiseras.
Krävs att front-end och back-end är igång för att kunna testa funktionalitetn, annars är det bara en svart ruta.

2021-05-15 20:11 UTC, NoraOdel approved these changes
Everything looks good.

2021-05-16 09:26 UTC, mikaelSahlestrom requested changes

2021-05-16 09:26 UTC, mikaelSahlestrom commented on user-application/src/components/UI/Canvas.js
> +  let runAnimation = false;
Vi får ett felmeddelande när vi använder runAnimation som komponentvariabel och inte som en statevariabel.
 _Assignments to the 'runAnimation' variable from inside React Hook useEffect will be lost after each render._ 

Skriv om som en statevariabel

2021-05-16 09:26 UTC, mikaelSahlestrom commented on user-application/src/components/UI/Canvas.js
>    };
Felmeddelande:
  _The 'animation' function makes the dependencies of useEffect Hook (at line 84) change on every render. Move it inside the useEffect callback._ 

Flytta in funktionen i useEffect hook

2021-05-16 09:26 UTC, mikaelSahlestrom commented on user-application/src/components/UI/Canvas.js
> +import React, { useRef, useEffect, } from "react";
Onödig line (flrmodligen från din auto-formaterare)

2021-05-16 09:45 UTC, mikaelSahlestrom approved these changes

2021-05-16 09:45 UTC, merged